# File: advanced_system_config.yaml

version: 1
validSensors:
  - input:temperature
  - input:humidity
  - temperature_c
  - temperature_f
  - humidity
  - pressure
  - pressure_kpa
  - dew_point
  - comfort_score
  - comfort_index
  - avg_temp_hum
  - combined_metric
  - humidity_status
  - battery_low_flag
  - system_overloaded
  - high_pressure_flag
  - device_info
  - complex_sensor
cycleTime: 100
redis:
  endpoints:
    - localhost:6379
  poolSize: 8
  retryCount: 3
  retryBaseDelayMs: 100
  connectTimeout: 5000
  syncTimeout: 1000
  keepAlive: 60
  password: null
  ssl: false
  allowAdmin: false
bufferCapacity: 200
# Enable extended mode for missing data interpolation
temporalMode:
  extendedLastKnown: true

# Dependency limits
maxDependencyDepth: 10

# Logging
logLevel: Information
logFile: logs/pulsar.log

# Metrics
metrics:
  enabled: true
  instanceName: advanced
  samplingIntervalSeconds: 30

# Health checks
healthCheck:
  enabled: true
  intervalSeconds: 60
  failureThreshold: 3
  timeoutMs: 2000
