validSensors:
  # Input sensors
  - input:temperature
  - input:fan_speed

  # Output sensors
  - output:sustained_high_temp
  - output:temp_spike
  - output:stress_alert
  - output:shutdown

  # Buffer sensors for temporal rules
  - buffer:temperature_history

# Evaluation cycle time in milliseconds
cycleTime: 100

# Redis configuration for data persistence and monitoring
redis:
  endpoints:
    - "localhost:6379"
  poolSize: 4
  retryCount: 3
  retryBaseDelayMs: 100
  connectTimeout: 5000
  syncTimeout: 1000
  keepAlive: 60
  password: null
  ssl: false
  allowAdmin: true  # enable admin for test flushing

# Maximum entries stored in buffers
bufferCapacity: 100
