version: 1
validSensors:
  - input:alpha
  - input:beta
  - input:gamma
  - output:alpha_high
  - output:beta_high
  - output:gamma_normal
  - output:ab_combined
  - output:ag_combined
  - output:final_alert
cycleTime: 100
redis:
  endpoints:
    - localhost:6379
  poolSize: 4
  retryCount: 3
  retryBaseDelayMs: 100
  connectTimeout: 5000
  syncTimeout: 1000
  keepAlive: 60
  password: null
  ssl: false
  allowAdmin: true
bufferCapacity: 0
