# File: Pulsar.Tests/RuntimeValidation/test-output/system_config.yaml
version: 1
validSensors:
  - input:a
  - input:b
  - input:c
  - output:sum
  - output:complex
cycleTime: 100  # ms
redis:
  endpoints: 
    - localhost:6379
  poolSize: 4
  retryCount: 3
  retryBaseDelayMs: 100
  connectTimeout: 5000
  syncTimeout: 1000
  keepAlive: 60
  password: null
  ssl: false
  allowAdmin: false
bufferCapacity: 100