# System configuration
system:
  name: FormatTestSystem
  version: 1.0.0
  description: System to test format handling in BeaconTester

# Allowed sensors (inputs and outputs)
sensors:
  outputs:
    # Boolean outputs
    - name: bool_true
      description: Boolean true value
    - name: bool_false
      description: Boolean false value
    - name: bool_numeric_true
      description: Numeric 1 (true)
    - name: bool_numeric_false
      description: Numeric 0 (false)
    - name: bool_string_true
      description: String "True"
    - name: bool_string_false
      description: String "False"
    - name: bool_yes
      description: String "yes" (true)
    - name: bool_no
      description: String "no" (false)
    
    # Numeric outputs
    - name: number_integer
      description: Integer value
    - name: number_decimal_period
      description: Decimal with period separator
    - name: number_decimal_comma
      description: Decimal with comma separator
    - name: number_scientific
      description: Scientific notation number
    - name: number_string
      description: Number as string
    - name: negative_number
      description: Negative number
    
    # String outputs
    - name: string_plain
      description: Plain string
    - name: string_whitespace
      description: String with whitespace
    - name: string_mixed_case
      description: String with mixed case
    - name: string_special_chars
      description: String with special characters

# Redis configuration
redis:
  host: localhost
  port: 6379
  password: null
  database: 0
  ssl: false
