version: 1

# System cycle time in milliseconds - how frequently rules are evaluated
cycleTime: 100

# Redis configuration for data persistence
redis:
  endpoints:
    - "localhost:6379"
  poolSize: 4
  retryCount: 3
  retryBaseDelayMs: 100
  connectTimeout: 5000
  syncTimeout: 1000
  keepAlive: 60
  password: null
  ssl: false
  allowAdmin: false

# Maximum number of entries in buffer sensors
bufferCapacity: 100
